import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Featured from '../components/Featured'
;

export default function Home() {
    return (
      <div className={styles.container}>
      <Head>
        <title>Uda | 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.iismargheritahackbaronissi.edu.it/sites/default/files/iis_1.png" />
      </Head>
      <Navbar />
      <Featured />
      <div className={styles.sectionsContainer}>
        <div className={styles.sec1}>
            <Link passHref href="class/2a">
              <h2>Classe 2A</h2>
            </Link>
        </div>
        <div className={styles.sec2}>
            <Link passHref href="class/2b">
              <h2>Classe 2B</h2>
            </Link>
        </div>
        <div className={styles.sec3}>
            <Link passHref href="class/2c">
              <h2>Classe 2C</h2>
            </Link>
        </div>
        <div className={styles.sec1}>
            <Link passHref href="class/2d">
              <h2>Classe 2D</h2>
            </Link>
        </div>
        <div className={styles.sec2}>
            <Link passHref href="class/2f">
              <h2>Classe 2F</h2>
            </Link>
        </div>
        <div className={styles.sec3}>
            <Link passHref href="class/2g">
              <h2>Classe 2G</h2>
            </Link>
        </div>
        </div>
      <Footer />
    </div>
  )
}
